pipeline {
    agent any
    tools {
        go 'go1.18'
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH_TAG'
        choice(
            name: 'ENV',
            choices: ['staging','production'],            
            description: 'deploy environtment'
        )
    }
    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0
    }
    stages {
		stage('Checkout') {
			steps {
				checkout([
					$class: 'GitSCM',
					branches: [[name: '*/${BRANCH}']],
                    credentialsId: 'gh-krobus00',
					clean: true,
					extensions: [],
					submoduleCfg: [],
					userRemoteConfigs: [[
					url: 'https://github.com/krobus00/go-test-service.git'
					]]
				])
			}
		}
        stage("Add config files") {
            steps {
                configFileProvider([configFile(fileId: "6c88279b-90c0-4e94-8432-cf8892b4871d", targetLocation: 'config.yml')]) {
                    sh "ls -lar"
                }
            }
        }
		stage('Code Analysis') {            
			steps {				
                withEnv(["PATH+GO=${HOME}/go/bin"]){
                    sh 'go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2'
                    sh 'make lint'
                }
            }
		}
        stage("Unit Test") {
            steps {
                sh 'make test'
            }
        }
		stage("Build Image") {
            steps {
                sh 'docker build . -t krobus00/go-test-service:staging'
            }
        }
        stage('Push to Docker Hub') {
            agent any
            steps {
                withCredentials([usernamePassword(credentialsId: 'dh-krobus00', passwordVariable: 'dockerhubPassword', usernameVariable: 'dockerhubUser')]) {
                sh "docker login -u ${env.dockerhubUser} -p ${env.dockerhubPassword}"
                sh 'docker push krobus00/go-test-service:staging'
                }
            }
        }
    }
	post {
        always {
            cleanWs()
            sh 'docker image prune --filter label=stage=builder'
        }
    }
}