apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-test-service
  template:
    metadata:
      labels:
        app: go-test-service
    spec:
      containers:
      - name: go-test-service
        image: krobus00/go-test-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000