apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-test
  template:
    metadata:
      labels:
        app: go-test
    spec:
      containers:
      - name: go-test
        image: krobus00/go-test-service:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/go-test-service server"]
        ports:
          - containerPort: 3000
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5